fix: fixed action

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -4,9 +4,13 @@ on:
   push:
     paths:
       - 'studio-kosmeo/studio-kosmeo/**'  # Aciona a action apenas se houver mudanças nessa pasta
+    branches:
+      - main
   pull_request:
     paths:
       - 'studio-kosmeo/studio-kosmeo/**'  # Também para pull requests
+    branches:
+      - main
 
 jobs:
   build:
@@ -18,16 +22,24 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: '18'  # Defina a versão do Node.js que você está utilizando
+          node-version: '20'  # Defina a versão do Node.js que você está utilizando
+
+      - name: Cache Yarn dependencies
+        uses: actions/cache@v2
+        with:
+          path: ~/.yarn/cache
+          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-
       
       - name: Install dependencies
         run: |
-          cd studio-kosmeo/studio-kosmeo
+          cd studio-kosmeo
           yarn
 
       - name: Build the project
         run: |
-          cd studio-kosmeo/studio-kosmeo
+          cd studio-kosmeo
           yarn build
 
       - name: Disable Jekyll on GitHub Pages
@@ -38,9 +50,17 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     needs: build  # O deploy depende do job de build
+    if: success()  # Só faz o deploy se o build for bem-sucedido
     steps:
       - name: Check out repository
         uses: actions/checkout@v2
+
+      - name: Check if build directory exists
+        run: |
+          if [ ! -d "studio-kosmeo/studio-kosmeo/out" ]; then
+            echo "Error: Build directory 'studio-kosmeo/studio-kosmeo/out' not found!"
+            exit 1
+          fi
       
       - name: Deploy to GitHub Pages
         uses: JamesIves/github-pages-deploy-action@v4
